### ISSUE TITLE
Upgrade to Modular logging (slf4j-2.0.0)

### ISSUE THREAD

**Issue by msgilligan** [SupernautApp/SupernautFX#22]
Besides Micronaut® Framework itself, the only non-modular library used by the Supernaut libraries and sample apps has been  `slf4j-api` 1.7.x and its implementation.

We should upgrade to slfj4-2.0.0 as soon as possible. There are currently alpha releases available, but I'm not sure if we want to use "alpha" versions.

**Comment by msgilligan** [comment]
I created branch `dependency-slf4j-2.0.0` for this upgrade and created draft PR #23. The implementation and integration was pretty smooth (once I figured out how to tweak the `mergedModule` settings in the sample apps to get Micronaut to use it, too.)

**Comment by msgilligan** [comment]
@FDelporte what do you think?

**Comment by FDelporte** [comment]
We had same problem in pi4j v2 project where slf4j is the only dependency and we decided to use 1.7.30. But will switch asap...

**Comment by msgilligan** [comment]
I'm going to try it in a few of my apps and see what happens.

**Comment by msgilligan** [comment]
slf4j-2.0.0-alpha5 seems to work fine in Supernaut.FX apps. It is also possible to override the transitive dependency that is declared in out published JARs. For these reasons -- and because targeting modular applications is a priority goal for Supernaut.FX, I'm going to go ahead and merge PR #23 and close this issue.
