### ISSUE TITLE
JavaFX HostServices "Open Link in Browser" doesn't work on macOS in GraalVM/Gluon

### ISSUE THREAD

**Issue by msgilligan** [SupernautApp/SupernautFX#25]
This has been fixed by https://bugs.openjdk.java.net/browse/JDK-8214158, which should be appearing in a JavaFX 18 Early Access build soon.  Thanks @mipastgt !

**Comment by mipastgt** [comment]
You are welcome :-)

**Comment by msgilligan** [comment]
I think Supernaut.FX will wait until JavaFX 18 is final to upgrade our (transitive) dependency. But applications needing this fix are free to update to newer/EA OpenJFX releases at any time.

I'll update the [supernaut-fx-sample-maven](https://github.com/SupernautApp/supernaut-fx-sample-maven) to OpenJFX 18 EA once the fix is released, see: https://github.com/SupernautApp/SupernautFX/issues/25

**Comment by msgilligan** [comment]
JavaFX 18 is released, but Supernaut.FX will not update its transitive dependency to 18, though the two sample apps (https://github.com/SupernautApp/supernaut-fx-sample-maven, https://github.com/SupernautApp/supernaut-fx-sample-gradle) have done so.

**Comment by msgilligan** [comment]
Closing. (As this is fixed upstream and requires no changes to Supernaut.FX to use the newer version.)
