### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by palexdev** [SupernautApp/SupernautFX#35]
Is it possible to disable the logger?
I tried placing this configuration in my resources folder but I can still see logs in my console
```
handlers=java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
java.util.logging.SimpleFormatter.format=%1$tH:%1$tM:%1$tS.%1$tL %4$-7s (%2$s) %n %5$s %6$s%n

java.util.logging.ConsoleHandler.level=OFF
app.level=OFF

app.supernaut.level=OFF
app.supernaut.fx.level=OFF
io.micronaut.context.level=OFF
```

**Comment by msgilligan** [comment]
> Is it possible to disable the logger? 

It should be. I'll try to produce an example in the sample app (https://github.com/SupernautApp/supernaut-fx-sample-gradle) that disables logging.

**Comment by msgilligan** [comment]
There is a utility class [JavaLoggingSupport.java](https://github.com/SupernautApp/SupernautFX/blob/master/modules/app.supernaut/src/main/java/app/supernaut/logging/JavaLoggingSupport.java) that can be used to configure logging in a way that is compatible both with OpenJDK and GraalVM `native-image` environments. [JavaLoggingSupport 0.40.0 JavaDoc](https://www.supernaut.app/SupernautFX/apidoc/app.supernaut/app/supernaut/logging/JavaLoggingSupport.html)

I have updated the Gradle and Maven samples to show how to use it:
* supernaut-fx-sample-gradle update: https://github.com/SupernautApp/supernaut-fx-sample-gradle/commit/b84be70ad3520f112a79eb0781d6982d5096e3d6
* supernaut-fx-sample-maven update: https://github.com/SupernautApp/supernaut-fx-sample-maven/commit/ff58f8fb598e0bfe84b4c94c3030a0b6247c4d3b

I've also cleaned up the JavaDoc a little and added a section in the user manual (these will be published in the next release): 88e98de5fc5e2b0213f228ad9a600e8e4505ade2

**Comment by msgilligan** [comment]
I'm closing the issue, but please let me know if this does not solve your problem.

**Comment by palexdev** [comment]
Hello, thanks for the quick response
It doesn't work for me, maybe I'm doing something wrong
However I fixed it by adding these three config lines to my `logback.xml`:
```xml
<logger name="app.supernaut.fx" level="OFF"/>
<logger name="io.micronaut.context" level="OFF"/>
<logger name="io.micronaut.core.reflect" level="OFF"/>
```

Thanks anyway but most importantly thank you very much for this awesome framework ;)

**Comment by msgilligan** [comment]
> my `logback.xml`:

Supernaut uses the SLF4J facade and the sample apps are using `java.util.logging` as the runtime implementation. Sounds like you are using a different runtime implementation, so the `JavaLoggingSupport` class won't work in that case.

> Thanks anyway but most importantly thank you very much for this awesome framework ;)

You're welcome!
